appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lXGSHaulilMuq9IQf74TNQkVW6FIjsJ/SohYdYlJUpTJYn6fJ6LSGuepeOQPeybWYrYuUSafluLXpVXI+jg2RpPliByyj5DjHCdZYQaCi6epmxdrBNz+iXlvWm59kSMhCTvMPpZFMJwUfRt7W4qOLLCWi1kgPs5taiksPSuWCnRqPVblR0PcQO4C/oK9Bd+oMS53tC54VL4mlH1NFMkk7M2HtsJ5+D4o0YITTALaybWP3PbR3PqpDA3eFka0jgWwY/mmN6ONU9NR0lEjaV/6tgGBJbclq1hAvYyWybPxsjn1m4aSHAktApjcA9R/UD99Dp5tpI5CS1i2e1pCCEqigWjMDN4/l4LBJQcFz8yjrQxjvttUR8LwKaSvjlD133HzM/bQtzR9AIp2n2fXxyBSdPqJD6GugveDrksbzeKISlPcWFKf1OYFZLevFzJ2tz32eEV+/N/Bsgu43UDOo17oc/yPHSsEQ54OojHakSeHaNKxkRwtpvO11Y17l4CW95mAy1Q2QMsVYALh1Uq1RmJiQsRFBjsxFVOVZtqK6CS3l14zGPKCsi8XEMV89UEFKbCznRBwyDfv+eWynFUjyxYpYQK2/ZAHmyOaMc5tZVygyVbW4bIC8bgvxRvDghzdmyEU8sjcV7KcTk+iSrfdv5rm1XcmceYP1fZAk1MB7vBqEpU=}
